### ISSUE TITLE
Ansible Samples Not Working

### ISSUE THREAD

**Issue by AlexNPavel** [operator-framework/operator-sdk-samples#41] opened 2018-10-30 20:58 UTC
At the moment, if you simply try to deploy the ansible images in the `ansible` directory of this repo (at least in the case of `etcd` and `memcached`), the operators do not start properly. The images should be updated and the `deploy/operator.yaml` files should point to the correct, working images.

**Comment by johnkim76** [comment] 2018-10-30 21:04
@AlexNPavel I believe this seems like this is a duplicate of [issue #40](https://github.com/operator-framework/operator-sdk-samples/issues/40)
This is will be fixed soon.

**Comment by darrylb-github** [comment] 2019-03-28 15:45
These ansible examples still seem broken. They work if I use the prepackaged docker images, e.g. `docker.io/dymurray/memcached-operator`, but if I try and build that image locally via `operator-sdk build darrylb/memcached-operator && docker push darrylb/memcached-operator` and use it in the deployment the operator keeps erroring out as below:

```
{
  "level": "error",
  "ts": 1553787627.899241,
  "logger": "kubebuilder.controller",
  "msg": "Reconciler error",
  "controller": "memcached-controller",
  "request": "default/example",
  "error": "the server could not find the requested resource",
  "stacktrace": "github.com/water-hole/ansible-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/travis/gopath/src/github.com/water-hole/ansible-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/water-hole/ansible-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/travis/gopath/src/github.com/water-hole/ansible-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/water-hole/ansible-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/travis/gopath/src/github.com/water-hole/ansible-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/water-hole/ansible-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/travis/gopath/src/github.com/water-hole/ansible-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/water-hole/ansible-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/travis/gopath/src/github.com/water-hole/ansible-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/water-hole/ansible-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/home/travis/gopath/src/github.com/water-hole/ansible-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"
}
```

**Comment by camilamacedo86** [comment] 2019-11-01 16:19
Hi @darrylb-github, 

The ansible sample was updated and then it sows fixed now. Please, feel free to check.

**Closed by camilamacedo86** 2019-11-01 16:19 UTC
Labels: kind/bug
